version: '3'

services:

    postgres:
        image: postgres:12.3 # latest on July 2020
        environment:
            - POSTGRES_USER=django
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        volumes:
            - ~/.pgdata/video-texter:/var/lib/postgresql/data
        #restart: always

    redis:
        image: redis:6.0.5 # latest on July 2020
        ports: 
            - 6379:6379


