version: '3'

services:

    web:
        build: .
        depends_on:
            - database
            - broker
        env_file: .env
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT}"
        ports:
            - 8000:${PORT}

    worker:
        build: .
        depends_on:
            - database
            - broker
        env_file: .env
        command: celery worker -A ${CELERY_APP} -l info

    database:
        image: postgres:12.3 # latest on July 2020
        env_file: .env
        expose:
            - 5432
        volumes:
            - "dbdata:/var/lib/postgresql/data"

    broker:
        image: redis:6.0.5 # latest on July 2020
        expose:  
            - 6379

volumes:
    dbdata:
