version: '3'

services:

    web:
        build: .
        depends_on:
            - database
            - broker
        command: python ./manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - .:/app

    worker:
        build: .
        depends_on:
            - database
            - broker
        command: celery worker -A video_texter -l info 


    database:
        image: postgres:12.3 # latest on July 2020
        environment:
            - POSTGRES_USER=django
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        volumes:
            - ~/.pgdata/video-texter:/var/lib/postgresql/data
        #restart: always

    broker:
        image: redis:6.0.5 # latest on July 2020
        ports: 
            - 6379:6379


