# Generated by Django 3.0.7 on 2020-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
