# Generated by Django 3.0.8 on 2020-07-02 17:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20200702_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubelink',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='youtubelink',
            name='title',
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
