# Generated by Django 3.0.8 on 2020-07-04 20:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20200702_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubelink',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
