# Generated by Django 3.0.8 on 2020-07-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_auto_20200705_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeVideoTask',
        ),
    ]
